// SET
export const SET_IS_APP_LOADING = 'SET_IS_APP_LOADING'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_SHOW_MESSAGE = 'SET_SHOW_MESSAGE'
export const SET_MESSAGE_TIMEOUT = 'SET_MESSAGE_TIMEOUT'

// ADD
export const ADD_AWAITING_EVENT = 'ADD_AWAITING_EVENT'

// REMOVE
export const REMOVE_AWAITING_EVENT = 'REMOVE_AWAITING_EVENT'
